# Generated by Django 3.0.8 on 2020-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_commander', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='dish_id',
        ),
        migrations.AddField(
            model_name='diet',
            name='dish_id',
            field=models.ManyToManyField(to='meal_commander.Dish'),
        ),
        migrations.RemoveField(
            model_name='diet',
            name='ingredient_id',
        ),
        migrations.AddField(
            model_name='diet',
            name='ingredient_id',
            field=models.ManyToManyField(to='meal_commander.Ingredient'),
        ),
    ]
