# Generated by Django 3.0.8 on 2020-08-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_commander', '0002_auto_20200804_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='dish_id',
        ),
        migrations.AddField(
            model_name='diet',
            name='dish_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meal_commander.Dish'),
        ),
    ]
