# Generated by Django 3.0.8 on 2020-08-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_commander', '0004_auto_20200804_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietingredientquantity',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_commander.Dish'),
        ),
        migrations.AlterField(
            model_name='dietingredientquantity',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_commander.Ingredient'),
        ),
    ]
