# Generated by Django 3.0.8 on 2020-08-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_commander', '0005_auto_20200804_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredient_id',
        ),
        migrations.AlterUniqueTogether(
            name='dietingredientquantity',
            unique_together={('dish_id', 'ingredient_id')},
        ),
    ]
