# Generated by Django 3.0.8 on 2020-08-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_commander', '0006_auto_20200805_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='at_plan',
            field=models.IntegerField(default=0),
        ),
    ]
