# Generated by Django 3.0.8 on 2020-08-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_commander', '0007_dish_at_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='meal_type',
            field=models.IntegerField(choices=[(0, '1st breakfest'), (1, '2nd breakfest'), (2, 'Dinner'), (3, 'Supper')], default=0),
        ),
    ]
