# Generated by Django 3.0.8 on 2020-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_commander', '0009_auto_20200813_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='actual_type',
            field=models.IntegerField(default=0),
        ),
    ]
